version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:casper@21@postgres:5432/project_hub
      NODE_ENV: development
      PORT: 8080
      POSTGRES_HOST: postgres  # New environment variable
    ports:
      - "8080:8080"
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: casper@21
      POSTGRES_DB: project_hub
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql